# Generated by Django 4.1.7 on 2023-06-05 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Airport",
            fields=[
                ("airport_id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Flight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="arrival_flights",
                        to="airline.airport",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FlightPassager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "flight",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="airline.flight"
                    ),
                ),
            ],
            options={
                "db_table": "airline_flight_passagers",
            },
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="arrival_routes",
                        to="airline.airport",
                    ),
                ),
                (
                    "flights",
                    models.ManyToManyField(related_name="routes", to="airline.flight"),
                ),
                (
                    "start",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departure_routes",
                        to="airline.airport",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Passager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=20)),
                ("surname", models.CharField(max_length=30)),
                (
                    "flights",
                    models.ManyToManyField(
                        related_name="passengers_flights",
                        through="airline.FlightPassager",
                        to="airline.flight",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passager_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="flightpassager",
            name="passager",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="airline.passager"
            ),
        ),
        migrations.AddField(
            model_name="flight",
            name="passengers",
            field=models.ManyToManyField(
                blank=True,
                related_name="flight_passager",
                through="airline.FlightPassager",
                to="airline.passager",
            ),
        ),
        migrations.AddField(
            model_name="flight",
            name="start",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="departure_flights",
                to="airline.airport",
            ),
        ),
        migrations.AddField(
            model_name="airport",
            name="arrivals",
            field=models.ManyToManyField(
                blank=True, related_name="arrival_airports", to="airline.flight"
            ),
        ),
        migrations.AddField(
            model_name="airport",
            name="departures",
            field=models.ManyToManyField(
                blank=True, related_name="departure_airports", to="airline.flight"
            ),
        ),
    ]
