# Generated by Django 4.1.7 on 2023-04-19 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='flights',
        ),
        migrations.AddField(
            model_name='route',
            name='flights',
            field=models.ManyToManyField(related_name='routes', to='airline.flight'),
        ),
    ]
