# Generated by Django 4.1.7 on 2023-06-05 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("airline", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flightpassager",
            name="flight",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Flight_Passager_flight",
                to="airline.flight",
            ),
        ),
        migrations.AlterField(
            model_name="flightpassager",
            name="passager",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Flight_Passager_passager",
                to="airline.passager",
            ),
        ),
    ]
