# Generated by Django 4.2.7 on 2023-12-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='airport_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
