# Generated by Django 4.2.7 on 2023-12-19 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0002_alter_airport_airport_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='value',
            field=models.TextField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
