# Generated by Django 4.2.7 on 2023-12-19 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0003_airport_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airport',
            name='value',
        ),
    ]
