# Dockerfile.apache
FROM httpd

# Enable proxy modules
RUN sed -i '/#LoadModule proxy_module/s/^#//g' /usr/local/apache2/conf/httpd.conf
RUN sed -i '/#LoadModule proxy_http_module/s/^#//g' /usr/local/apache2/conf/httpd.conf

# Copy Apache configuration file
COPY apache/httpd.conf /usr/local/apache2/conf/httpd.conf
