# Generated by Selenium IDE
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from django.contrib.staticfiles.testing import StaticLiveServerTestCase

class TestAirlineuser(StaticLiveServerTestCase):
  def setUp(self):

    options = webdriver.FirefoxOptions()
    options.add_argument('--headless')
    self.driver = webdriver.Firefox(options=options)
    self.vars={}
  
  def tearDown(self):
    self.driver.quit()
  
  def test_full_map_no_existing_country(self):
    self.driver.get("http://localhost:8000/")
    self.driver.find_element(By.NAME, "start_country").send_keys("qqqqqqqqqq")
    self.driver.find_element(By.ID, "check_flight").click()
    self.driver.find_element(By.ID, "main_site").click()
    self.driver.close()
  
  def test_full_map(self):
    self.driver.get("http://localhost:8000/")
    self.driver.find_element(By.NAME, "start_country").send_keys("Poland")
    self.driver.find_element(By.ID, "check_flight").click()
    self.driver.switch_to.frame(0)
    self.driver.find_element(By.CSS_SELECTOR, "g > .leaflet-interactive:nth-child(1)").click()
    self.driver.find_element(By.LINK_TEXT, "Route \'64\' Details")
    self.driver.switch_to.default_content()
    self.driver.find_element(By.LINK_TEXT, "If you prefer table view, click here").click()
    self.driver.close()
 
  def test_user_profile(self):
    self.driver.get("http://localhost:8000/")
    self.driver.find_element(By.NAME, "username").send_keys("test")
    self.driver.find_element(By.NAME, "psw").send_keys("test")
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(3)").click()
    self.driver.find_element(By.NAME, "Passager").click()
    self.driver.find_element(By.TAG_NAME, "h1")
    self.driver.close()

  def test_airport_flight_route_chain(self):
    self.driver.get("http://127.0.0.1:8000/airline/airport/140")
    self.driver.find_element(By.CSS_SELECTOR, "a.link-dark").click()
    self.driver.find_element(By.XPATH, "/html/body/section[1]/div[1]/div[2]/div/a").click()
    self.driver.find_element(By.XPATH, "/html/body/header/h1/a[3]").click()
    self.driver.close()

  def test_admin_mode(self):
    self.driver.get("http://localhost:8000/")
    self.driver.find_element(By.NAME, "username").send_keys("admin")
    self.driver.find_element(By.NAME, "psw").send_keys("admin")
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(3)").click()
    self.driver.find_element(By.XPATH, "/html/body/nav/div/ul/li[2]/a").click()
    self.driver.find_element(By.XPATH, "/html/body/nav/div/ul/li[3]/a").click()
    time.sleep(2)
    self.driver.find_element(By.XPATH, "/html/body/nav/div/ul/li[1]/a").click()
    self.driver.close()
