# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUser():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_user(self):
    self.driver.get("http://localhost:8000/")
    self.driver.set_window_size(970, 1045)
    self.driver.find_element(By.NAME, "username").click()
    self.driver.find_element(By.NAME, "username").send_keys("A")
    self.driver.find_element(By.NAME, "psw").click()
    self.driver.find_element(By.NAME, "psw").send_keys("A")
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(3)").click()
    self.driver.find_element(By.LINK_TEXT, "Sign Up").click()
    self.driver.find_element(By.CSS_SELECTOR, ".form-group > .form-control:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".form-group > .form-control:nth-child(2)").send_keys("Test")
    self.driver.find_element(By.NAME, "firstname").send_keys("Test")
    self.driver.find_element(By.NAME, "lastname").send_keys("Test")
    self.driver.find_element(By.CSS_SELECTOR, ".form-control:nth-child(8)").send_keys("Test")
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary:nth-child(4)").click()
    self.driver.find_element(By.ID, "start_country").click()
    self.driver.find_element(By.ID, "start_country").click()
    element = self.driver.find_element(By.ID, "start_country")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.ID, "start_country").send_keys("Belgium")
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
    self.driver.find_element(By.LINK_TEXT, "Check Every Possible Flight on Our Airline").click()
    self.driver.find_element(By.LINK_TEXT, "30/09/2023").click()
    self.driver.find_element(By.LINK_TEXT, "Manihiki Island Airport").click()
    self.driver.find_element(By.LINK_TEXT, "6").click()
    self.driver.find_element(By.LINK_TEXT, "6").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
    self.driver.find_element(By.ID, "id_context").click()
    self.driver.find_element(By.ID, "id_context").send_keys("Test")
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bi-person").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(1)").click()
    self.driver.find_element(By.LINK_TEXT, "Logout").click()
    self.driver.close()
  
